ENV_DATA:
  platform: 'baremetalpsi'
  deployment_type: 'upi'
  flexy_img_url: 'docker-registry.upshift.redhat.com/aosqe/flexy:poc'

# Override flexy params here
FLEXY:
  default_private_conf_repo: 'git@gitlab.cee.redhat.com:ocs/flexy-ocs-private.git'
  flexy_private_conf_url: ''
  # Volume which will be attached to instance,
  # which will be consumed for osd. (size in GB)
  volume_size: 500
  # Use this variable in case a local flexy env file
  # needs to be used (through '--flexy-env-file' cli option)
  flexy_env_file: ''
