---
# Config file for nightly OCP 4.4
RUN:
  client_version: '4.4.0-0.nightly'
DEPLOYMENT:
  installer_version: "4.4.0-0.nightly"
ENV_DATA:
  vm_template: 'rhcos-4.4.0-x86_64-vmware'

# rhcos_ami version for aws upi deployments will be fetched from
# https://raw.githubusercontent.com/openshift/installer/release-4.4/data/data/rhcos.json
